@baseUrl = http://127.0.0.1:3001

# Recados

### MessagesController -> Retorna todos os recados

GET {{baseUrl}}/messages/
?limit=101
&offset=300


### ### MessagesController -> Retorna um recado
GET {{baseUrl}}/messages/2

### MessagesController -> Cria um novo recado
POST {{baseUrl}}/messages
Content-Type: application/json

{
  "text": "create new messages",
  "from": "Jhon",
  "to": "Maria",
  "read": false,
  "date": "2024-10-31T10:18:24.807Z"
}

### MessagesController -> atualiza um recado
PATCH  {{baseUrl}}/messages/2
Content-Type: application/json

{
  "text": "update messages",
  "from": "Jhon",
  "to": "Maria",
  "read": true,
  "date": "2024-10-31T10:18:24.807Z"
}

### MessagesController -> Deleta um recado
DELETE   {{baseUrl}}/messages/2
Content-Type: application/json
