@baseUrl = http://127.0.0.1:3001

# Recados

### MessagesController -> Retorna todos os recados

GET {{baseUrl}}/messages/
?limit=101
&offset=300


### ### MessagesController -> Retorna um recado
GET {{baseUrl}}/messages/2

### MessagesController -> Cria um novo recado
POST {{baseUrl}}/messages
Content-Type: application/json

{
  "text": "create new messages",
  "from": "Jhon",
  "to": "Maria"
}

### MessagesController -> atualiza um recado
PATCH  {{baseUrl}}/messages/3
Content-Type: application/json

{
  "text": "update messages",
  "read": true
}

### MessagesController -> Deleta um recado
DELETE   {{baseUrl}}/messages/1
Content-Type: application/json


# User

### UserController -> Busca todos user
GET {{baseUrl}}/users

### UserController -> Busca um user espeficado pelo id
GET {{baseUrl}}/messages/2

### UserController -> Cria um novo user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Jhon Doe",
  "email": "jhoedoe@gmail.com",
  "password": "123456"
}

### UserController -> Atualizar um usuário

PATCH  {{baseUrl}}/users/3
Content-Type: application/json

{
  "text": "update messages",
  "read": true
}


### UserController -> Deleta um usuário

DELETE   {{baseUrl}}/users/1
Content-Type: application/json