@baseUrl = http://127.0.0.1:3001

# Recados

### MessagesController -> Retorna todos os recados

GET {{baseUrl}}/messages/
?limit=3
&offset=2


### ### MessagesController -> Retorna um recado
GET {{baseUrl}}/messages/16

### MessagesController -> Cria um novo recado
POST {{baseUrl}}/messages
Content-Type: application/json

{
  "text": "Enviando um recado para Jhon",
  "fromId": 1,
  "toId": 3
}

### MessagesController -> atualiza um recado
PATCH  {{baseUrl}}/messages/18
Content-Type: application/json

{
  "text": "Enviando um recado para João 2",
  "read": false
}

### MessagesController -> Deleta um recado
DELETE   {{baseUrl}}/messages/18
Content-Type: application/json


# User

### UserController -> Busca todos user
GET {{baseUrl}}/users

### UserController -> Busca um user espeficado pelo id
GET {{baseUrl}}/messages/2

### UserController -> Cria um novo user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Joao",
  "email": "joao2@gmail.com",
  "password": "123456"
}

### UserController -> Atualizar um usuário

PATCH  {{baseUrl}}/users/7
Content-Type: application/json

{
  "name": "Diego",
  "password": "654321"
}


### UserController -> Deleta um usuário

DELETE   {{baseUrl}}/users/8
Content-Type: application/json